cart/urls.py
from os import name

from myproject.settings import MEDIA_ROOT
from . import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path(
        "remove_cart/<int:product_id>/", views.remove_cart, name="remove_cart"
    ),
    path(
        "delete_cart/<int:product_id>/", views.delete_cart, name="delete_cart"
    ),
    path("checkout", views.checkout, name="checkout"),
    path(
        "check_coupen/<grand_total>", views.check_coupen, name="check_coupen"
    ),
]

myproject/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from order.models import Order

urlpatterns = [
    path("sadmin/", admin.site.urls),
    path("tadmin/", include("admin.urls")),
    path("vendor/", include("vendors.urls")),
    path("", include("user.urls")),
    path("shop/", include("store.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("order.urls")),
]

user/forms.py
from django import forms
from django.contrib.messages.api import error
from django.db.models import fields

from user.models import Address, Profile


class AddAdddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = (
            "first_name",
            "last_name",
            "phone",
            "email",
            "address1",
            "address2",
            "country",
            "state",
            "city",
            "pincode",
            "add_type",
        )

    def __init__(self, *args, **kwargs):
        super(AddAdddressForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(
        required=False,
        error_messages={"invalid": ("Images Only")},
        widget=forms.FileInput,
    )

    class Meta:
        model = Profile
        fields = ("first_name", "last_name", "email", "profile_picture")

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"

templates/user_dashboard/address.html
{% extends 'base.html'%} {% load static %} {% block content %}
<nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">My Account</li>
        </ol>
    </div><!-- End .container -->
</nav><!-- End .breadcrumb-nav -->

<div class="page-content">
    <div class="dashboard">
        <div class="container">
            <div class="row">
                {% include 'user_dashboard/user_base.html' %}

                <div class="col-lg-10 col-md-10  mt-4 mt-lg-0">
                    <div class="tab-content">
                        <div class="tab-pane show active" id="tab-address" role="tabpanel"
                            aria-labelledby="tab-address-link">
                            <div class="col-md-12">
                                <div class="accordion accordion-icon" id="accordion-3">
                                    <div class="card">
                                        <div class="card-header" id="heading3-1">
                                            <h2 class="card-title">
                                                <a class="collapsed" role="button" data-toggle="collapse"
                                                    href="#collapse3-1" aria-expanded="false"
                                                    aria-controls="collapse3-1">
                                                    <i class="icon-add-o"></i>{% if check %}
                                                    <span>Update Address</span>
                                                    {% else %}
                                                    <span>Add Address</span>
                                                    {% endif %}
                                                </a>
                                            </h2>
                                        </div><!-- End .card-header -->
                                        <div id="collapse3-1" class="collapse {% if check %}
                                        show
                                        {% endif %}" aria-labelledby="heading3-1" data-parent="#accordion-3">
                                            <div class="card-body">
                                                <form action="" method="POST" id="address-form">
                                                    {% csrf_token %}
                                                    <div class="row">
                                                        <div class="col-sm-6">
                                                            <label>First Name *</label>
                                                            {{form.first_name}}
                                                        </div><!-- End .col-sm-6 -->

                                                        <div class="col-sm-6">
                                                            <label>Last Name *</label>
                                                            {{form.last_name}}
                                                        </div><!-- End .col-sm-6 -->
                                                        <div class="col-sm-6">
                                                            <label>Phone*</label>
                                                            {{form.phone}}
                                                        </div>
                                                        <div class="col-sm-6">
                                                            <label>Email*</label>
                                                            {{form.email}}
                                                        </div>
                                                        <div class="col-sm-12">
                                                            <label>Address 1*</label>
                                                            {{form.address1}}
                                                        </div>
                                                        <div class="col-sm-12">
                                                            <label>Address 2*</label>
                                                            {{form.address2}}
                                                        </div>
                                                        <div class="col-sm-4">
                                                            <label>City *</label>
                                                            {{form.city}}
                                                        </div>
                                                        <div class="col-sm-4">
                                                            <label>State *</label>
                                                            {{form.state}}
                                                        </div>
                                                        <div class="col-sm-4">
                                                            <label>Country *</label>
                                                            {{form.country}}
                                                        </div>
                                                        <div class="col-sm-8">
                                                            <label>Pin Code *</label>
                                                            {{form.pincode}}
                                                        </div>
                                                        <div class="col-sm-4">
                                                            <label>Address Type *</label>
                                                            {{form.add_type}}
                                                        </div>
                                                    </div><!-- End .row -->



                                                    <button type="submit" class="btn btn-outline-primary-2">
                                                        {% if check %}
                                                        <span>Update Address</span>
                                                        {% else %}
                                                        <span>Add Address</span>
                                                        {% endif %}
                                                        <i class="icon-long-arrow-right"></i>
                                                    </button>
                                                </form>
                                            </div><!-- End .card-body -->
                                        </div><!-- End .collapse -->
                                    </div><!-- End .card -->


                                </div><!-- End .accordion -->
                                <!-- End .col-md-6 -->
                                <p>The following addresses can be used on the checkout page by default.</p>
                                {% if check %}
                                {% else %}
                                <div class="row ">

                                    {% for x in address %}
                                    <div class="col-sm-6">

                                        <div class="card card-dashboard">

                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <p><b>{{x.first_name}} {{x.last_name}}</b></p>
                                                        <div class="col-md-12">
                                                            <span>{{x.address1}} ,</span>
                                                            <span>{{x.address2}}</span>
                                                            <span>{{x.city}}, {{x.state}}, {{x.country}}</span>
                                                            <p>Pin : {{x.pincode}}</p>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-12 d-flex flex-column justify-content-between">
                                                        <div class="d-flex justify-content-between">
                                                            <p class="mb-1 text-primary"><b>{{x.add_type}}</b></p>

                                                            <p>{{x.phone}}</p>
                                                        </div>
                                                        <div class="btn-group">
                                                            <button type="button"
                                                                class="btn btn-primary dropdown-toggle"
                                                                data-toggle="dropdown" aria-haspopup="true"
                                                                aria-expanded="false">
                                                                Action
                                                            </button>
                                                            <div class="dropdown-menu">
                                                                <a class="dropdown-item" onclick="confirmAddress(event)"
                                                                    href="{% url 'edit_address' x.id %}"
                                                                    title="edit">Edit</a>
                                                                <a class="dropdown-item" onclick='confirmAddress(event)'
                                                                    href="{% url 'delete_address' x.id %}"
                                                                    title="delete">Delete</a>
                                                            </div>
                                                        </div>


                                                    </div>

                                                </div>

                                            </div><!-- End .card-body -->



                                        </div>
                                    </div><!-- End .col-lg-6 -->
                                    {% endfor %}

                                </div><!-- End .row -->
                                {% endif %}
                            </div><!-- .End .tab-pane -->

                        </div>
                    </div><!-- End .col-lg-9 -->
                </div><!-- End .row -->
            </div><!-- End .container -->
        </div><!-- End .dashboard -->
    </div><!-- End .page-content -->
</div>

<script>
    function confirmAddress(event) {
        event.preventDefault();
        var linkURL = event.currentTarget.href;
        var action = event.currentTarget.title;
        console.log(linkURL);
        console.log(action)
        Swal.fire({
            title: "Do you want to " + action + " this address ? ",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: 'primary',
            cancelButtonColor: 'success',
            confirmButtonText: 'Yes, ' + action + ' !'
        })
            .then((result) => {
                if (result.isConfirmed) {
                    window.location = linkURL;
                } else {
                    return false;
                }
            });
    }
</script>
<style>
    .error{
        color: red;
    }
</style>
<script>
    $(document).ready(function ($) {
        console.log("hai");
        $("#address-form").validate({
            rules: {
                first_name:{
                    required: true
                },
                last_name:{
                    required: true
                },
                email: {
                    required: true,
                    email: true
                },
                address1:{
                    required:true
                },
                city:{
                    required:true
                },
                state:{
                    required:true
                },
                pincode:{
                    required:true,
                    minlength:6,
                    maxlength:6
                },
                phone:{
                    required:true,
                    minlength:10,
                    maxlength:10
                },
            },
            messages: {
                email:{
                    required: "Please enter your email",
                },
                phone:{
                    required:"Please enter a phone number",
                    minlength:"Please provide a valid number",
                    maxlength:"Please provide a valid number"
                },
                pincode:{
                    required:"Pincode is required ",
                    minlength:"Please provide a valid pincode",
                    maxlength:"Please provide a valid pincode"
                },
                
            },
            submitHandler: function (form) {
                form.submit();
            }

        });
    });
    
</script>


{% endblock %}

templates/user_dashboard/dashboard.html
{% extends 'base.html'%} {% load static %} {% block content %}
<nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">My Account</li>
        </ol>
    </div><!-- End .container -->
</nav><!-- End .breadcrumb-nav -->

<div class="page-content">
    <div class="dashboard">
        <div class="container">
            <div class="row">
                {% include 'user_dashboard/user_base.html' %}

                <div class="col-lg-10 col-md-10  mt-4 mt-lg-0">
                    <div class="row justify-content-around">
                        <div class="col-md-4 col-sm-6">
                            <div class="card border">
                                <div class="p-5 ">
                                    <div class="col-md-12 text-center">

                                        <h3 class="text-primary"><b>{{total_orders}}</b></h3>

                                    </div>
                                    <div class="col-sm-12 text-center">
                                        <h5 class="text-primary"><b>Total Orders</b></h5>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class=" p-5">
                                    <div class="col-md-12 row">
                                        <div class="col-md-6 text-primary">
                                            <h4>{{usr_profile.first_name}} {{usr_profile.last_name}}</h4>
                                            <h5>{{usr_profile.email}}</h5>
                                        </div>
                                            <div class="col-md-4 p-3 text-right ">
                                                <img src="{{usr_profile.profile_picture.url}}" alt="profile_picture" width="50vh" height="50vh" style="border-radius: 10px;">
                                            
                                            </div>
                                            
                                    </div>

                            </div>
                        </div>
                    </div>
                </div><!-- End .col-lg-9 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
    </div><!-- End .dashboard -->
</div><!-- End .page-content -->

{% endblock %}

templates/user_dashboard/profile.html
{% extends 'base.html'%} {% load static %} {% block content %}
<nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">My Account</li>
        </ol>
    </div><!-- End .container -->
</nav><!-- End .breadcrumb-nav -->

<div class="page-content">
    <div class="dashboard">
        <div class="container">
            <div class="row">
                {% include 'user_dashboard/user_base.html' %}



                <div class="col-lg-10 col-md-10  mt-4 mt-lg-0">

                    <div class="card-body">
                        <form action="" method="POST" enctype='multipart/form-data'>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-9 col-sm-12 row">
                                    <div class="col-sm-6">
                                        <label>First Name *</label>
                                        {{form.first_name}}
                                    </div><!-- End .col-sm-6 -->

                                    <div class="col-sm-6">
                                        <label>Last Name *</label>
                                        {{form.last_name}}
                                    </div><!-- End .col-sm-6 -->
                                    <div class="col-sm-6">
                                        <label>Gender *</label>
                                        <input type="text" class="form-control" value="{{usr_profile.gender}}" disabled>
                                    </div>
                                    <div class="col-sm-6 text-center align-items-center ">
                                        <label class="my-5 btn btn-dark " for="id_profile_picture">Change
                                            Profile Picture*</label>
                                        {{form.profile_picture}}
                                    </div>
                                    <div class="col-sm-12">
                                        <label>Email address *</label>
                                        {{form.email}}

                                    </div>
                                </div>

                                <div class="col-sm-3 col-md-3">
                                    <img style="border-radius: 150px;" width="150vh" height="150vh"
                                        src="{{usr_profile.profile_picture.url}}" alt="">
                                </div>
                            </div><!-- End .row -->



                            <button type="submit" class="btn btn-outline-primary-2">
                                <span>Update Profile</span>
                                <i class="icon-long-arrow-right"></i>
                            </button>
                        </form>
                    </div><!-- End .card-body -->
                </div><!-- End .row -->
            </div><!-- End .container -->
        </div><!-- End .dashboard -->
    </div><!-- End .page-content -->
</div>

<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js" type="text/javascript"></script>

{% endblock %}

templates/user_dashboard/reset_password.html
{% extends 'base.html'%} {% load static %} {% block content %}
<nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">My Account</li>
        </ol>
    </div><!-- End .container -->
</nav><!-- End .breadcrumb-nav -->

<div class="page-content">
    <div class="dashboard">
        <div class="container">
            <div class="row">
                {% include 'user_dashboard/user_base.html' %}

                <div class="col-lg-10 col-md-10  mt-4 mt-lg-0">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="col-md-6 justify-content-center">
                            <input type="password" name="current_password" placeholder="current password" required
                                class="form-control">
                            <input type="password" name="new_password" placeholder="New password" required
                                class="form-control">
                            <input type="password" name="confirm_password" placeholder="Confirm password" required
                                class="form-control">
                            <input type="submit" class="btn btn-outline-primary-2 mt-1" value="Update Password">
                        </div>

                    </form>

                </div><!-- End .row -->
            </div><!-- End .container -->
        </div><!-- End .dashboard -->
    </div><!-- End .page-content -->
</div>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js" type="text/javascript"></script>

{% endblock %}

templates/user_dashboard/user_base.html
<aside class="col-md-2 col-lg-2">
    <ul class="nav nav-dashboard flex-column mb-3 mb-md-0" role="tablist">
        <li class="nav-item">
            <a class="nav-link {% if '/dashboard' == request.path %}active{% endif %} " href="{% url 'dashboard' %}"
                role="tab" aria-controls="tab-dashboard" aria-selected="true">Dashboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if '/user_order' == request.path %}active{% endif %}" href="{% url 'user_order' %}"
                role="tab" aria-controls="tab-orders" aria-selected="false">Orders</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if '/user_address' == request.path %}active{% endif %}"
                href="{% url 'user_address' %}" role="tab" aria-controls="tab-address"
                aria-selected="false">Adresses</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if '/user_profile' == request.path %}active{% endif %}"
                href="{% url 'user_profile' %}" role="tab" aria-controls="tab-account" aria-selected="false">My
                Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if '/change_password' == request.path %}active{% endif %}"
                href="{% url 'change_password' %}" role="tab" aria-controls="tab-account" aria-selected="false">Change
                Password</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" onclick="singout(event)" href="{% url 'signout' %}">Sign Out</a>
        </li>
    </ul>
</aside><!-- End .col-lg-3 -->
<script>
    function signout(event) {
        event.preventDefault();
        var linkURL = event.currentTarget.href;
        Swal.fire({
            title: "Do you want to Signout ? ",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: 'primary',
            cancelButtonColor: 'success',
            confirmButtonText: 'Yes, Cancel !'
        })
            .then((result) => {
                if (result.isConfirmed) {
                    window.location = linkURL;
                } else {
                    return false;
                }
            });
    }
</script>